apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: x9wwgr6hv-nodejs
  janus-idp.io/tekton: x9wwgr6hv-nodejs
  backstage.io/kubernetes-id: x9wwgr6hv-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: x9wwgr6hv-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
