apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: x9wwgr6hv-nodejs 
  janus-idp.io/tekton: x9wwgr6hv-nodejs
  backstage.io/kubernetes-id: x9wwgr6hv-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: x9wwgr6hv-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml